-- KBase Core v1 - persistent schema (DB-02)
-- Source of truth: docs/design-docs/KBase - Core v1 Physical Database Design.md (sections 4-23)
-- 10 persistent tables. No OTP table: OTP verification state is Redis-only short-lived state;
-- the durable verification result lives in users.email_verified_at.
-- UUIDs are generated by the application (no gen_random_uuid() default), per design section 2.

-- Section 4: users
CREATE TABLE users (
    id              UUID PRIMARY KEY,

    email           VARCHAR(254) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    display_name    VARCHAR(100) NOT NULL,

    system_role     VARCHAR(20) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    email_verified_at TIMESTAMPTZ NULL,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_users_email
        UNIQUE (email),

    CONSTRAINT ck_users_email_normalized
        CHECK (
            email = LOWER(BTRIM(email))
            AND email <> ''
        ),

    CONSTRAINT ck_users_display_name
        CHECK (
            display_name = BTRIM(display_name)
            AND display_name <> ''
        ),

    CONSTRAINT ck_users_system_role
        CHECK (system_role IN ('ADMIN', 'USER')),

    CONSTRAINT ck_users_status
        CHECK (status IN ('ACTIVE', 'DISABLED'))
);

-- Section 5: refresh_sessions (PostgreSQL-backed; Redis never replaces refresh sessions)
CREATE TABLE refresh_sessions (
    id              UUID PRIMARY KEY,

    user_id         UUID NOT NULL,

    token_hash      VARCHAR(128) NOT NULL,

    expires_at      TIMESTAMPTZ NOT NULL,
    revoked_at      TIMESTAMPTZ NULL,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_refresh_sessions_token_hash
        UNIQUE (token_hash),

    CONSTRAINT fk_refresh_sessions_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_refresh_sessions_expiration
        CHECK (expires_at > created_at)
);

-- Section 6: projects (no owner_id: OWNER lives in project_members.role)
CREATE TABLE projects (
    id              UUID PRIMARY KEY,

    name            VARCHAR(150) NOT NULL,
    description     TEXT NULL,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_projects_name
        CHECK (
            name = BTRIM(name)
            AND name <> ''
        )
);

-- Section 7: project_members
CREATE TABLE project_members (
    id              UUID PRIMARY KEY,

    project_id      UUID NOT NULL,
    user_id         UUID NOT NULL,

    role            VARCHAR(20) NOT NULL,

    joined_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_project_members_project_user
        UNIQUE (project_id, user_id),

    CONSTRAINT fk_project_members_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_project_members_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_project_members_role
        CHECK (role IN ('OWNER', 'MEMBER'))
);

-- Section 9: project_invitations (token_hash only; raw invitation token is never stored)
CREATE TABLE project_invitations (
    id                  UUID PRIMARY KEY,

    project_id          UUID NOT NULL,
    invited_by_user_id  UUID NOT NULL,

    email               VARCHAR(254) NOT NULL,
    token_hash          VARCHAR(128) NOT NULL,

    status              VARCHAR(20) NOT NULL,

    expires_at          TIMESTAMPTZ NOT NULL,
    accepted_at         TIMESTAMPTZ NULL,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_project_invitations_token_hash
        UNIQUE (token_hash),

    CONSTRAINT fk_project_invitations_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_project_invitations_inviter
        FOREIGN KEY (invited_by_user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_project_invitations_email
        CHECK (
            email = LOWER(BTRIM(email))
            AND email <> ''
        ),

    CONSTRAINT ck_project_invitations_status
        CHECK (
            status IN (
                'PENDING',
                'ACCEPTED',
                'EXPIRED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_project_invitations_expiration
        CHECK (expires_at > created_at),

    CONSTRAINT ck_project_invitations_accepted_at
        CHECK (
            (status = 'ACCEPTED' AND accepted_at IS NOT NULL)
            OR
            (status <> 'ACCEPTED' AND accepted_at IS NULL)
        )
);

-- Section 11: folders (composite parent FK enforces same-project parent, section 12)
CREATE TABLE folders (
    id              UUID PRIMARY KEY,

    project_id      UUID NOT NULL,
    parent_id       UUID NULL,

    name            VARCHAR(150) NOT NULL,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_folders_id_project
        UNIQUE (id, project_id),

    CONSTRAINT fk_folders_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_folders_parent_same_project
        FOREIGN KEY (parent_id, project_id)
        REFERENCES folders(id, project_id)
        ON DELETE NO ACTION,

    CONSTRAINT ck_folders_name
        CHECK (
            name = BTRIM(name)
            AND name <> ''
        ),

    CONSTRAINT ck_folders_not_self_parent
        CHECK (
            parent_id IS NULL
            OR parent_id <> id
        )
);

-- Section 15: categories
CREATE TABLE categories (
    id              UUID PRIMARY KEY,

    project_id      UUID NOT NULL,

    name            VARCHAR(100) NOT NULL,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_categories_id_project
        UNIQUE (id, project_id),

    CONSTRAINT fk_categories_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_categories_name
        CHECK (
            name = BTRIM(name)
            AND name <> ''
        )
);

-- Section 16: tags
CREATE TABLE tags (
    id              UUID PRIMARY KEY,

    project_id      UUID NOT NULL,

    name            VARCHAR(50) NOT NULL,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_tags_id_project
        UNIQUE (id, project_id),

    CONSTRAINT fk_tags_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_tags_name
        CHECK (
            name = BTRIM(name)
            AND name <> ''
        )
);

-- Section 17: documents (uploaded_by references users, not project_members, section 18;
-- composite folder/category FKs prevent cross-project assignment, section 19)
CREATE TABLE documents (
    id                      UUID PRIMARY KEY,

    project_id              UUID NOT NULL,
    uploaded_by_user_id     UUID NOT NULL,

    folder_id               UUID NULL,
    category_id             UUID NULL,

    display_name            VARCHAR(255) NOT NULL,
    original_filename       VARCHAR(255) NOT NULL,

    file_kind               VARCHAR(20) NOT NULL,

    extension               VARCHAR(20) NOT NULL,
    mime_type               VARCHAR(150) NOT NULL,
    size_bytes              BIGINT NOT NULL,

    storage_key             VARCHAR(1024) NOT NULL,

    description             TEXT NULL,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_documents_storage_key
        UNIQUE (storage_key),

    CONSTRAINT uq_documents_id_project
        UNIQUE (id, project_id),

    CONSTRAINT fk_documents_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_documents_uploader
        FOREIGN KEY (uploaded_by_user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_documents_folder_same_project
        FOREIGN KEY (folder_id, project_id)
        REFERENCES folders(id, project_id)
        ON DELETE NO ACTION,

    CONSTRAINT fk_documents_category_same_project
        FOREIGN KEY (category_id, project_id)
        REFERENCES categories(id, project_id)
        ON DELETE NO ACTION,

    CONSTRAINT ck_documents_display_name
        CHECK (
            display_name = BTRIM(display_name)
            AND display_name <> ''
        ),

    CONSTRAINT ck_documents_original_filename
        CHECK (original_filename <> ''),

    CONSTRAINT ck_documents_file_kind
        CHECK (
            file_kind IN (
                'DOCUMENT',
                'IMAGE',
                'VIDEO'
            )
        ),

    CONSTRAINT ck_documents_extension
        CHECK (
            extension = LOWER(BTRIM(extension))
            AND extension <> ''
        ),

    CONSTRAINT ck_documents_size
        CHECK (size_bytes > 0),

    CONSTRAINT ck_documents_storage_key
        CHECK (storage_key <> '')
);

-- Section 23: document_tags (project_id column enforces same-project document/tag pairing, section 24)
CREATE TABLE document_tags (
    document_id     UUID NOT NULL,
    tag_id          UUID NOT NULL,
    project_id      UUID NOT NULL,

    CONSTRAINT pk_document_tags
        PRIMARY KEY (document_id, tag_id),

    CONSTRAINT fk_document_tags_document_same_project
        FOREIGN KEY (document_id, project_id)
        REFERENCES documents(id, project_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_document_tags_tag_same_project
        FOREIGN KEY (tag_id, project_id)
        REFERENCES tags(id, project_id)
        ON DELETE CASCADE
);
